{
 "title": "深圳到全国监测点速率",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "电信丢包率 (%)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "smokeping_lost_package_num{ISP=\"TELCOM\",instance=~\".*\",exported_job=\"smokeping-collected-TELCOM\",alias=~'.*'}/20*100",
     "legendFormat": "{{ alias }}"
    }
   ]
  },
  {
   "title": "联通丢包率 (%)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "smokeping_lost_package_num{ISP=\"UNICOM\",instance=~\".*\",exported_job=\"smokeping-collected-UNICOM\" , alias=~'.*'} / 20 * 100",
     "legendFormat": "{{ alias }}"
    }
   ]
  },
  {
   "title": "移动丢包率 (%)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "smokeping_lost_package_num{ISP=\"CMCC\",instance=~\".*\",exported_job=\"smokeping-collected-CMCC\" , alias=~'.*'} / 20 * 100",
     "legendFormat": "{{ alias }}"
    }
   ]
  },
  {
   "title": "网易丢包率 (%)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "smokeping_lost_package_num{ISP=\"WY\",instance=~\".*\",exported_job=\"smokeping-collected-WY\" , alias=~'.*'} / 20 * 100",
     "legendFormat": "{{ alias }}"
    }
   ]
  },
  {
   "title": "电信延迟top10 (ms)",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "topk(10,smokeping_rrt{IDC=\"SH\",ISP=\"TELCOM\",instance=~\".*\",exported_job=\"smokeping-collected-TELCOM\",alias=~\".*\"})",
     "legendFormat": "{{ alias }}"
    }
   ]
  },
  {
   "title": "联通延迟top10 (ms)",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "expr": "topk(10 , smokeping_rrt{IDC=\"SH\",ISP=\"UNICOM\",instance=~\".*\",exported_job=\"smokeping-collected-UNICOM\" , alias=~'.*'})",
     "legendFormat": "{{ alias }}"
    }
   ]
  },
  {
   "title": "移动延迟top10 (ms)",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "topk(10 , smokeping_rrt{IDC=\"SH\",ISP=\"CMCC\",instance=~\".*\",exported_job=\"smokeping-collected-CMCC\" , alias=~'.*'})",
     "legendFormat": "{{ alias }}"
    }
   ]
  },
  {
   "title": "网易延迟top10 (ms)",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "topk(5 , smokeping_rrt{IDC=\"SH\",ISP=\"WY\",instance=~\".*\",exported_job=\"smokeping-collected-WY\" , alias=~'.*'})",
     "legendFormat": "{{ alias }}"
    }
   ]
  },
  {
   "title": "电信延迟一览 (ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "smokeping_rrt{IDC=\"SH\",ISP=\"TELCOM\",instance=~\".*\",exported_job=\"smokeping-collected-TELCOM\" , alias=~'.*'}",
     "legendFormat": "{{ alias }}"
    }
   ]
  },
  {
   "title": "联通延迟一览 (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "smokeping_rrt{IDC=\"SH\",ISP=\"UNICOM\",instance=~\".*\",exported_job=\"smokeping-collected-UNICOM\" , alias=~'.*'}",
     "legendFormat": "{{ alias }}"
    }
   ]
  },
  {
   "title": "移动延迟一览 (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "smokeping_rrt{IDC=\"SH\",ISP=\"CMCC\",instance=~\".*\",exported_job=\"smokeping-collected-CMCC\" , alias=~'.*'}",
     "legendFormat": "{{ alias }}"
    }
   ]
  },
  {
   "title": "网易延迟一览 (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "smokeping_rrt{IDC=\"SH\",ISP=\"WY\",instance=~\".*\",exported_job=\"smokeping-collected-WY\" , alias=~'.*'}",
     "legendFormat": "{{ alias }}"
    },
    {
     "expr": "smokeping_lost_package_num{ISP=\"WY\",instance=~\".*\",exported_job=\"smokeping-collected-WY\" , alias=~'.*'} / 20 * 100",
     "legendFormat": "{{ alias }}"
    }
   ]
  }
 ]
}